spring:
  application:
    name: web-service  
  freemarker:
    enabled: false

eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 3333